# Tier A sweep — mid-size text models on the 8-GPU spot box.
# MODEL|TP|GPUS|MAXLEN|CACHE|TIERS|EXTRA_VLLM_ARGS
# GLM first (BF16, no quant constraints). Qwen3-FP8: block-quantized MoE is NOT
# TP-shardable at TP=8 (block_n=128 vs 192-wide shards -> SE-11); EP shards by
# whole expert instead. Excluded: Mistral-Large (MRL license). Scout appended
# (access approved; multimodal -> full tiers, launched with SKIP_COMMERCIAL=0).
zai-org/GLM-4.5-Air|8|8|16384|230Gi|clean-digital|
Qwen/Qwen3-235B-A22B-Instruct-2507-FP8|8|8|16384|250Gi|clean-digital|--enable-expert-parallel
